### ISSUE TITLE
Error TP 

### ISSUE THREAD

**Issue by Scrulius** [anjoismysign/BlobStones#1]
Hola Blob, me encanta tu plugin, he estado testeándolo y me da un error a la hora de hacer TP a mis piedras:

https://pastebin.com/BTYKcu2D

Para generar el error, simplemente abres el menú de blobstones, seleccionas una de tus piedras y le das a teletransportar, da ese error en consola y tampoco teletransporta.

Mi versión de servidor es: 1.20.1 Paper 176 (la más reciente)
Mi versión de ProtectionStones es: 2.10.3
Mi versión de Worldguard es: 7.0.9
Mi versión de Bloblib es: 1.691.1s

Un saludo y gracias! Te he dejado 5 estrellas en Spigot porque está realmente bueno tu plugin!

**Comment by anjoismysign** [comment]
Ejecuta
`/bloblib update BlobStones`
Avísame si el problema persiste

**Comment by Scrulius** [comment]
> Ejecuta `/bloblib update BlobStones` Avísame si el problema persiste

Yep, el TP ya funciona, el problema ahora es que la cuenta atrás está mal, empieza por -17, luego -18, luego -19, luego 1 y luego te teletransporta

Genera este error en consola https://pastebin.com/4PdWi5iU

**Comment by anjoismysign** [comment]
`/bloblib update BlobStones`
Si el error persiste, necesito latest.log dentro de la carpeta logs.
No me importa si tu log dice que haces algo inmoral, me importa corregir el problema.
También necesitaría un poco más de detalles, más precisión a la hora de detallar el error. De la poca información no encontré relación con algo en el código (al menos en la parte de que empezara a contar en -17 y al llegar a -20 brincara a +1 y luego tirara error)

Lo corregiría en mi localhost pero estoy ejercitando.
Puedes agregarme a Discord (anjoismysign) y así avisarme más rápido cuando respondas. Aquí en GitHub con suerte he logrado ver de una a dos horas después que comentaras.

Muchas gracias por confiar en mi desarrollo 😄

Edit: Didn't work since it didn't reference a valid message. I was not able to compile in my own computer (was not at home), so I did a few workflows to automate such a process.

**Comment by anjoismysign** [comment]
`/bloblib update BlobStones`
Si el error persiste me avisas.
De lo contrario cierro el issue.
